### ISSUE TITLE
Project Base Setup

### ISSUE THREAD

**Issue by beausmith** [votingworks/react-anywhereballot#1]
Let's use this issue to track tasks related to the setup and config of this repo.

Please add more to this issue as you see fit.

# Tasks
- [x] Init with Create React App
- [ ] Add static analysis with ESLint and Prettier
- [ ] Setup Jest for testing.
- [ ] Setup Flow

# Questions
- Which version of React to use? Should we use v16.7.0-alpha so we can use hooks, etc?
- Use TypeScript vs JavaScript + Flow?

As we make decisions, they can be recorded in the README.
